#!/usr/bin/env bash
# This script prints a message forever and ignores SIGTERM by printing "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
