#!/usr/bin/env bash
# This script writes "I am alive!" to /tmp/my_process indefinitely

LOG_FILE="/tmp/my_process"
touch "$LOG_FILE"

while true; do
  echo "I am alive!" >> "$LOG_FILE"
  sleep 2
done
